services:
  #  kafka:
  #    image: confluentinc/cp-kafka:7.5.5
  #    container_name: kafka-confluentinc
  #    hostname: kafka
  #    ports:
  #      - "9092:9092"
  #      - "9094:9094"
  #    environment:
  #      - KAFKA_NODE_ID=1
  #      - KAFKA_PROCESS_ROLES=broker,controller
  #      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
  #      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094
  #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
  #      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #      - KAFKA_LOG_DIRS=/var/lib/kafka/data
  #      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
  #      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
  #      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
  #      - KAFKA_NUM_PARTITIONS=3
  #    volumes:
  #      - kafka_data:/var/lib/kafka/data
  #    networks:
  #      - app_network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - ES_INDEX=zipkin-index
      - JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  kafka_data: