services:

  # ================================
  # KAFKA
  # ================================
  kafka:
    image: confluentinc/cp-kafka:7.5.5
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 735f3SGQT9a-p5Z0O6Gh2A
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app_network

  # ================================
  # MYSQL
  # ================================
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 30

  # ================================
  # POSTGRES
  # ================================
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 30

  # ================================
  # MONGO
  # ================================
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - app_network

  # ================================
  # EUREKA
  # ================================
  eureka-server:
    image: datdevv/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - app_network
    depends_on:
      kafka:
        condition: service_started

  # ================================
  # API GATEWAY
  # ================================
  api-gateway:
    image: datdevv/api-gateway:latest
    ports:
      - "6789:6789"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app_network

  # ================================
  # MICROSERVICES
  # ================================
  iam-service:
    image: datdevv/iam-service:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - app_network

  patient-service:
    image: datdevv/patient-service:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - app_network

  testorder-service:
    image: datdevv/testorder-service:latest
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - app_network

  warehouse-service:
    image: datdevv/warehouse-service:latest
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - app_network

  instrument-service:
    image: datdevv/instrument-service:latest
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - app_network

  monitoring-service:
    image: datdevv/monitoring-service:latest
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - app_network

  notification-service:
    image: datdevv/notification-service:latest
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started
    networks:
      - app_network

  # ================================
  # PROMETHEUS
  # ================================
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - '--config.file=/prometheus.yml'
    volumes:
      - ./prometheus.yml:/prometheus.yml
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app_network:
    driver: bridge

volumes:
  kafka_data:
  mongodb_data:
  mysql_data:
  postgres_data:
