global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'iam-service'
    metrics_path: '/iam/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
  - job_name: 'another-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
        'host.docker.internal:8082',
        'host.docker.internal:8083'
      ]
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:6789' ]
