spring:
  config:
    import: classpath:.env.properties
  datasource:
    url: jdbc:mysql://mysql:3306/testorder_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #kafka
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVER:kafka:9092}
    consumer:
      group-id: testOrder-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    #        spring.json.value.default.type: ttldd.event.dto.PatientUpdateEvent
    listener:
      missing-topics-fatal: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

server:
  port: 8083
  servlet:
    context-path: /testorder

app:
  patient-service:
    url: http://patient-service:8082
  iam-service:
    url: http://iam-service:8081/iam
  security:
    encryption-key: ${CRYPTO_SECRET_KEY}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


