spring:
  application:
    name: BE

  datasource:

    url: jdbc:mysql://localhost:3306/lab_manager
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #flyway migration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  # Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: codemaster3979@gmail.com

    password: bnzrqpzdxjfknmxk

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
        debug: false
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 4193282944223723
            client-secret: 775ece03a76088607c5cd356eba19ced
            redirect-uri: "${FACEBOOK_REDIRECT_URI:https://localhost:3000/auth/social/callback/facebook}"
            auth-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
            response-type: code
            scope:
              - email
              - public_profile

          google:
            client-id: "${GOOGLE_CLIENT_ID:1061123444145-ga7gecn3snrnrvkg79fvp759n5iq8ibd.apps.googleusercontent.com}"
            client-secret: "${GOOGLE_CLIENT_SECRET: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}"
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:3000/auth/social/callback/google}"
            auth-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://www.googleapis.com/oauth2/v3/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            scope:
              - email
              - public_profile

jwt:
  secret: nXT5iZ/lPUY/9T4pgt3zqCJkezyP0if70mQbfJlz1k8=
  expiration: 86400

admin:
  email: admin@admin.com
  password: Admin123

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082
