name: Build & Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            iam:
              - 'iam-service/**'
            patient:
              - 'patient-service/**'
            testorder:
              - 'testorder-services/**'
            warehouse:
              - 'warehouse-service/**'
            instrument:
              - 'instrument-service/**'
            monitoring:
              - 'monitoring-service/**'
            notification:
              - 'notification-service/**'
            gateway:
              - 'api-gateway/**'
            eureka:
              - 'discovery-server/**'
      - name: Create .env.properties from Secret
        run: |
          echo "${{ secrets.ENV_PROPERTIES_BASE64 }}" | base64 -d > env_temp.properties
          
          mkdir -p ./iam-service/src/main/resources
          cp env_temp.properties ./iam-service/src/main/resources/.env.properties
          
          mkdir -p ./notification-service/src/main/resources
          cp env_temp.properties ./notification-service/src/main/resources/.env.properties

          mkdir -p ./testorder-services/src/main/resources
          cp env_temp.properties ./testorder-services/src/main/resources/.env.properties

          rm env_temp.properties

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # IAM SERVICE
      - name: Build IAM Service
        if: steps.changes.outputs.iam == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./iam-service
          file: ./iam-service/Dockerfile
          push: true
          tags: ngothanhdatak/iam-service:latest

      # PATIENT SERVICE
      - name: Build Patient Service
        if: steps.changes.outputs.patient == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./patient-service
          file: ./patient-service/Dockerfile
          push: true
          tags: ngothanhdatak/patient-service:latest

      # TESTORDER SERVICE
      - name: Build TestOrder Service
        if: steps.changes.outputs.testorder == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./testorder-services
          file: ./testorder-services/Dockerfile
          push: true
          tags: ngothanhdatak/testorder-service:latest

      # WAREHOUSE SERVICE
      - name: Build Warehouse Service
        if: steps.changes.outputs.warehouse == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./warehouse-service
          file: ./warehouse-service/Dockerfile
          push: true
          tags: ngothanhdatak/warehouse-service:latest

      # INSTRUMENT SERVICE
      - name: Build Instrument Service
        if: steps.changes.outputs.instrument == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./instrument-service
          file: ./instrument-service/Dockerfile
          push: true
          tags: ngothanhdatak/instrument-service:latest

      # MONITORING SERVICE
      - name: Build Monitoring Service
        if: steps.changes.outputs.monitoring == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./monitoring-service
          file: ./monitoring-service/Dockerfile
          push: true
          tags: ngothanhdatak/monitoring-service:latest

      # NOTIFICATION SERVICE
      - name: Build Notification Service
        if: steps.changes.outputs.notification == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile
          push: true
          tags: ngothanhdatak/notification-service:latest

      # API GATEWAY
      - name: Build API Gateway
        if: steps.changes.outputs.gateway == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ngothanhdatak/api-gateway:latest

      # EUREKA SERVER
      - name: Build Eureka Service
        if: steps.changes.outputs.eureka == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./discovery-server
          file: ./discovery-server/Dockerfile
          push: true
          tags: ngothanhdatak/eureka-service:latest
